### ISSUE TITLE
run error on install react-native-media-suite

### ISSUE THREAD

**Issue by oakcreations** [digital-waterfall/react-native-media-suite#3]
react-native-cli: 2.0.1
react-native: 0.57.7

warning: the transform cache was reset.
Loading dependency graph...(node:19008) UnhandledPromiseRejectionWarning: Error: jest-haste-map:Haste module naming collision:
  Duplicate module name: react-native
  Paths: /Users/infra/Documents/project/medcelareadoalunov4/node_modules/rn-multi-tenant-async-storage/node_modules/react-native/package.json collides with /Users/infra/Documents/project/medcelareadoalunov4/node_modules/react-native/package.json

This error is caused by `hasteImpl` returning the same name for different files.
    at setModule (/Users/infra/Documents/project/medcelareadoalunov4/node_modules/jest-haste-map/build/index.js:551:17)
    at workerReply (/Users/infra/Documents/project/medcelareadoalunov4/node_modules/jest-haste-map/build/index.js:613:9)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:19008) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promisewhich was not handled with .catch(). (rejection id: 2)
(node:19008) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zeroexit code.
(node:19008) UnhandledPromiseRejectionWarning: Error: jest-haste-map: Haste module naming collision:
  Duplicate module name: react-native
  Paths: /Users/infra/Documents/project/medcelareadoalunov4/node_modules/rn-multi-tenant-async-storage/node_modules/react-native/package.json collides with /Users/infra/Documents/project/medcelareadoalunov4/node_modules/react-native/package.json

This error is caused by `hasteImpl` returning the same name for different files.
    at setModule (/Users/infra/Documents/project/medcelareadoalunov4/node_modules/jest-haste-map/build/index.js:551:17)
    at workerReply (/Users/infra/Documents/project/medcelareadoalunov4/node_modules/jest-haste-map/build/index.js:613:9)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:19008) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promisewhich was not handled with .catch(). (rejection id: 3)

**Comment by craig95** [comment]
This is a problem in the [rn-multi-tenant-async-storage](https://github.com/digital-waterfall/rn-multi-tenant-async-storage) package. react-native is a dependency and not a peer dependency. I will fix this within the next day.

**Comment by oakcreations** [comment]
thx @craig95

**Comment by erickbank** [comment]
SAME PROBLEM ,  HELP ME PLEASE

**Comment by craig95** [comment]
I have pushed a fix. I believe it should work. Closing the issue, if it is still a problem please reopen the issue.
